### ISSUE TITLE
Datacenter list accuracy

### ISSUE THREAD

**Issue by devxzero** [Umkus/ip-index#1]
Your datacenter list (https://github.com/Umkus/ip-index/blob/master/dist/datacenters.netset) is incredible large. I'm wondering how accurate it is. 

I programmatically counted the number of IP-addresses that is cover. It's: 1.273.450.192
While the ipcat dataset (https://github.com/client9/ipcat) *only* contains 95.959.476.
The number of IP-addresses in your dataset is 30% of the complete IPv4 address space. So the datacenter dataset is soo large that it is hard to belief that it can be that large. It would mean that at least 30% of all theoretically available IPv4 addresses are currently owned by datacenters.

**Comment by Umkus** [comment]
Hello,

I just updated the README.md to address your question.
In short I used publicly available DC data and matching ASN names.
Doing a quick sanity-check shows that ouf of 10 random IPs all 10 are deemed suspicious by 3rd party services.

What I'm planning to do is go through the list of the ~1.7k ASNs (`src/matches.js`) and double-check all of them, since that's the only thing I'm not too certain. I just took those numbers for other projects for the most part. Everything else does have a target keyword (cloud/dedi/server/vpn/...) in the AS name to be considered a DC.

False positives are well possible. I do occasionally find an ASN that shouldn't be banned.
