### ISSUE TITLE
Why does this not contain anything from Nord or ExpressVPN

### ISSUE THREAD

**Issue by ghost** [Umkus/ip-index#18]
I checked your netset file for multiple IPs from Nord VPN, NONE of them are in the list.

![image](https://user-images.githubusercontent.com/93844225/142824778-1caf3777-cd0c-4202-8454-f2f0619101be.png)
![image](https://user-images.githubusercontent.com/93844225/142824957-7203e602-a252-4cc4-8a39-be34db1c972d.png)

Try it for yourself https://nordvpn.com/de/servers/tools/

**Comment by ghost** [comment]
I own ExpressVPN myself and Looked up a Few ips after reconnecting to different Servers, none of the IPs are in the list.

**Comment by ghost** [comment]
For anyone wanting an test for VPNs use https://focsec.com That actually works, it detected all the IPs as VPNs

**Comment by Umkus** [comment]
Hello,

1. You should check the `datacenters.netset`, not `blacklisted.netset`.
2. You are unable to find an __exact string match__, because there are no individual IP addresses in that file, only IP ranges.

I just manually checked and it did detect my NordVPN IP perfectly fine. The database is [explicitly being built](https://github.com/Umkus/ip-index/blob/master/src/build.js#L181) with a fresh set of NordVPN IPs.

You can use [this script](https://github.com/Umkus/ip-index/blob/master/src/example.js) to test your IPs.
