### ISSUE TITLE
Question about the swap from Sqlite

### ISSUE THREAD

**Issue by ptibom** [Umkus/ip-index#39]
Hello, I'm using an old version of your repo with the sqlite file.

I'm just curious why you made the decision to swap from sqlite?

(Trying to decide if I should keep it or go with your new system.)

Thank you

**Comment by Umkus** [comment]
IIRC, less setup, less hassle building for the target arch, less maintenance effort in general, since sqlite3 binary file no longer needs to be bundled.
At first I couldn't figure out how to process and query large CSVs fast, so I cheated with sqlite3.
It's a bit of an overkill for the project overall

**Comment by ptibom** [comment]
Thank you. If you don't mind explaining (briefly), what was the solution to process CSVs fast?

**Comment by Umkus** [comment]
For example when parsing the CSV I take the first octet in each range and use it to group all records by.
This gives 255 buckets of ranges, scoping the amount to iterate over. This could be improved further, but I stopped as soon as I saw couple-millisecond query performance on my machine.
