### ISSUE TITLE
[Advice] Best practices for running this in production

### ISSUE THREAD

**Issue by arpowers** [Umkus/ip-index#6]
Very nice looking tool you've put together here. We are looking at using this for an analytics service. 

How would you recommend this tool be implemented in production, e.g. with AWS?

**Comment by Umkus** [comment]
Hello.

The way I'm using it is just as in the `example.js`, with help of the [better-sqlite3](https://github.com/JoshuaWise/better-sqlite3) npm module. When I ran it in AWS (lambda) I used a lambda layer. If your workload is already running on lambdas, then you are done, just follow the `example.js` setup. Otherwise you could setup an API GW to proxy requests to the lambda, that returns the needed IP information. Then access the info via the API endpoint.

**Comment by Umkus** [comment]
Check the commented out code: https://github.com/Umkus/ip-index/blob/master/.github/workflows/build.yml#L51
Be advised that this deploys the REST (v1) of the API Gateway, lambda and layer. You could get away with a cheaper (and simpler) setup if you use HTTP Api (v2). I'll try to updat that part eventually.
